// English adjectives describing star properties
// Comprehensive list of ~200 stellar adjectives

const STAR_ADJECTIVES = [
  'active',
  'aglow',
  'amber',
  'ancient',
  'ascending',
  'astral',
  'beaming',
  'beautiful',
  'binary',
  'blazing',
  'blue',
  'blue-giant',
  'blue-green',
  'blue-white',
  'blurred',
  'bright',
  'brightest',
  'brilliant',
  'burning',
  'celestial',
  'circumpolar',
  'clear',
  'close',
  'cold',
  'common',
  'compact',
  'constant',
  'cool',
  'coolest',
  'cosmic',
  'dazzling',
  'dense',
  'dim',
  'dimmest',
  'distant',
  'dormant',
  'double',
  'drifting',
  'dull',
  'dwarf',
  'effulgent',
  'emerging',
  'enchanting',
  'energetic',
  'enigmatic',
  'enormous',
  'erupting',
  'eternal',
  'ethereal',
  'everlasting',
  'evolved',
  'exceptional',
  'explosive',
  'extraordinary',
  'fading',
  'faint',
  'famous',
  'far',
  'faraway',
  'farthest',
  'feeble',
  'fiery',
  'fixed',
  'flaring',
  'flashing',
  'focused',
  'frigid',
  'gaseous',
  'gentle',
  'giant',
  'gleaming',
  'glimmering',
  'glistening',
  'glittering',
  'glowing',
  'golden',
  'hazy',
  'heavenly',
  'hot',
  'hottest',
  'huge',
  'icy',
  'immortal',
  'inactive',
  'incandescent',
  'infinite',
  'intense',
  'invisible',
  'ionized',
  'irregular',
  'large',
  'largest',
  'luminous',
  'lustrous',
  'magnetic',
  'main-sequence',
  'majestic',
  'massive',
  'metallic',
  'mighty',
  'moving',
  'multiple',
  'mysterious',
  'mystical',
  'naked-eye',
  'nascent',
  'near',
  'nearby',
  'nearest',
  'nebulous',
  'neutron',
  'newborn',
  'notable',
  'nuclear',
  'old',
  'oldest',
  'orange',
  'orbiting',
  'ordinary',
  'pale',
  'peaceful',
  'perpetual',
  'polar',
  'powerful',
  'proximate',
  'pulsar',
  'pulsating',
  'radiant',
  'rare',
  'red',
  'red-giant',
  'refulgent',
  'regular',
  'remarkable',
  'remote',
  'resplendent',
  'rising',
  'rotating',
  'scintillating',
  'scorching',
  'serene',
  'setting',
  'sharp',
  'shimmering',
  'shining',
  'silent',
  'silvery',
  'single',
  'small',
  'smallest',
  'solitary',
  'sparkling',
  'spinning',
  'stable',
  'stationary',
  'steady',
  'stellar',
  'sublime',
  'supergiant',
  'telescopic',
  'timeless',
  'tiny',
  'tranquil',
  'triple',
  'twinkling',
  'unblinking',
  'unique',
  'unstable',
  'unusual',
  'variable',
  'violent',
  'visible',
  'volatile',
  'wandering',
  'waning',
  'warm',
  'waxing',
  'weak',
  'white',
  'yellow',
  'young',
  'youngest',
] as const;

type StarAdjective = (typeof STAR_ADJECTIVES)[number];

// Category groupings
const STAR_ADJECTIVE_CATEGORIES = {
  brightness: ['bright', 'brilliant', 'blazing', 'dazzling', 'luminous', 'dim', 'faint'] as const,
  color: ['red', 'blue', 'white', 'yellow', 'orange', 'golden', 'silvery'] as const,
  size: ['massive', 'giant', 'supergiant', 'enormous', 'huge', 'dwarf', 'compact'] as const,
  distance: ['distant', 'remote', 'far', 'near', 'nearby', 'close'] as const,
  age: ['ancient', 'old', 'young', 'newborn'] as const,
  temperature: ['hot', 'cold', 'cool', 'warm', 'fiery', 'burning', 'icy'] as const,
  behavior: ['variable', 'pulsating', 'stable', 'constant', 'explosive', 'volatile'] as const,
  poetic: ['celestial', 'cosmic', 'ethereal', 'mystical', 'majestic', 'beautiful'] as const,
} as const;

export { STAR_ADJECTIVES, STAR_ADJECTIVE_CATEGORIES };
export type { StarAdjective };